### ISSUE TITLE
8400可以用么

### ISSUE THREAD

**Issue by ghost** [yinxianwei/Hackintosh#1]
你好 谢谢上传 请问8400可以用这个efi么 同款主板

**Comment by yinxianwei** [comment]
> 你好 谢谢上传 请问8400可以用这个efi么 同款主板

核显一样应该是可以的吧，可以试一下

**Comment by ghost** [comment]
谢谢 我已经用上了 目前感觉完全完美 没有使用您的readme中的pmset操作 也能正常睡眠 那个是不是不一定要设置啊？

**Comment by yinxianwei** [comment]
正常的话不用设置
