### ISSUE TITLE
big sur支持

### ISSUE THREAD

**Issue by Kur0x** [yinxianwei/Hackintosh#4]
大佬，有没有试过big sur，我卡在IOkit stall XHC，估计是我自己搞的usb map有问题，你这个usb map 能用于big sur 么

**Comment by yinxianwei** [comment]
> 大佬，有没有试过big sur，我卡在IOkit stall XHC，估计是我自己搞的usb map有问题，你这个usb map 能用于big sur 么

我的系统是: Big Sur 11.3 (20E232)， 你可以看下[更新记录](https://github.com/yinxianwei/Hackintosh/releases)

**Comment by Kur0x** [comment]
好的，那我试试。那Monterey支持吗？

yinxianwei ***@***.***>于2021年10月29日 周五下午3:18写道：

**Comment by yinxianwei** [comment]
还没有升级哦~如果升级了我会更新的
